#! /bin/bash
#
# debian/tests/smoke-python3
# Part of Debian ‘python-coverage’ package.
#
# Copyright © 2016 Ben Finney <bignose@debian.org>
# This is free software; you may copy, modify, and/or distribute this work
# under the terms of the Expat license as published by James Clark.
# No warranty expressed or implied.
#
# Smoke test for package in Python 3 environments.

set -o errexit
set -o errtrace
set -o nounset

DISTRIBUTION_NAME=coverage
MODULE_NAMES=(
        coverage
        )

test_opts="--distribution=$DISTRIBUTION_NAME"
for mod in ${MODULE_NAMES[@]} ; do
    # Accumulate the module names.
    test_opts="$test_opts --module=$mod"
done

for py in $(py3versions -i) ; do
    printf "Python command: %s\n" $py
    $py debian/tests/smoke_test.py $test_opts
    printf "\n"
done


# Local variables:
# coding: utf-8
# mode: shell-script
# End:
# vim: fileencoding=utf-8 filetype=sh :
